name: Rust

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'     
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Setup enviornment
        run: |
          rustup target install aarch64-apple-ios
          rustup target install aarch64-apple-ios-sim
          rustup target install x86_64-apple-ios
          rustup target install aarch64-apple-darwin
          rustup target install x86_64-apple-darwin
          cargo install cargo-lipo
      
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
          
      - name: Build xcframework
        run: |
          cd tun2socks
          make xcframework
          zip Tun2SocksFramework.xcframework.zip Tun2SocksFramework.xcframework
          cd ../
          cp tun2socks/Tun2SocksFramework.xcframework.zip Tun2SocksFramework.xcframework.zip
          ls -l
